"use client";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";
import { TodoProvider } from "@/contexts/TodoContext";
import { Provider } from "react-redux";
import Store from "@/Store";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={Store}>
          <TodoProvider>
            <Header />
            {children}
          </TodoProvider>
        </Provider>
      </body>
    </html>
  );
}
